### ISSUE TITLE
Write callbacks do not work if PvaServer and Channel use the same interpreter

### ISSUE THREAD

**Issue by jjaraalm** [epics-base/pvaPy#46]
This does not work and will cause python to hang:

```python
data = PvObject({'value': INT}, {'value': 1})
server = PvaServer('foo', data, print)
channel = Channel('foo')
channel.put(data)
```

However, creating a server without a write callback works fine.

**Comment by jjaraalm** [comment]
I'm not very familiar with boost-python, but my understanding is that the GIL is automatically acquired by boost-python when calling methods, so `Channel::put` has the GIL, but `PyPvRecord::process` needs it to complete (and to finish the synchronous put). So I think the GIL needs to be released before calling any of the `pvaClient` put/get methods?

**Comment by sveseli** [comment]
Resolved in 1.4.0 release.

**Comment by jjaraalm** [comment]
Hi, thanks for working on this so quickly. It's a corner case, but this still does not work correctly if both channel monitors and write callbacks are used simultaneously.

That is,
``` python
data = PvObject({'value': INT}, {'value': 1})
server = PvaServer('foo', data, print)
channel = Channel('foo')
channel.subscribe('print', print)
channel.startMonitor()
channel.put(data)
```

will now hang. Using only one of either a channel monitor or a write callback works fine. In practice, this is not an issue for me, but still unexpected.

**Comment by sveseli** [comment]
This should work if you enable monitor queue using something like channel.setMonitorMaxQueueLength(10).  Please give it a try and let me know.

**Comment by jjaraalm** [comment]
Ok, that works. Thanks,
